AVR_TOOLS_DIR = /opt/local
ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
ARDMK_DIR     = /Users/karotka/Arduino/make/
PROJECT_DIR   = /Users/karotka/Arduino
USER_LIB_PATH := $(PROJECT_DIR)/libraries
AVRDUDE_ISP_BAUDRATE = 115200

ISP_PROG     = stk500v2
#ISP_PORT      = /dev/tty.wchusbserial*
ISP_PORT      = /dev/tty.usbmodem*
BOARD_TAG     = mega
MCU           = atmega2560

include /Users/karotka/Arduino/make/Arduino.mk
