AVR_TOOLS_DIR = /opt/local
ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
ARDMK_DIR     = /Users/karotka/Arduino/make/
PROJECT_DIR   = /Users/karotka/Arduino
USER_LIB_PATH := $(PROJECT_DIR)/libraries

ISP_PORT      = /dev/cu.*
BOARD_TAG     = mega
MCU           = atmega2560

include /Users/karotka/Arduino/make/Arduino.mk
