AVR_TOOLS_DIR = /opt/local
ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
ARDMK_DIR     = /Users/karotka/Arduino/make/
PROJECT_DIR   = /Users/karotka/Arduino
USER_LIB_PATH := $(PROJECT_DIR)/libraries
AVRDUDE_ISP_BAUDRATE = 57600

ISP_PROG     = stk500
ISP_PORT      = /dev/tty.wchusbserial1410
MCU           = atmega328p

include /Users/karotka/Arduino/make/Arduino.mk
