UPLOAD_PORT = /dev/tty.wchusbserial141240
#UPLOAD_PORT = /dev/tty.wchusbserial1430
#UPLOAD_PORT = /dev/tty.SLAB_USBtoUART
#UPLOAD_SPEED = 460800
BOARD=d1_mini
FS_DIR=data
VERBOSE = 1
include /Users/karotka/Arduino/make.esp/makeEspArduino.mk
