UPLOAD_PORT = /dev/tty.usbserial-14130
UPLOAD_SPEED = 460800
BOARD=d1_mini
BUILD_DIR=build
VERBOSE=1
FLASH_DEF=4M1M
FS_TYPE=spiffs
FS_DIR=data

include /Users/karotka/Arduino/make.esp/makeEspArduino.mk
