UPLOAD_PORT = /dev/tty.wchusbserial14130
#UPLOAD_PORT = /dev/tty.SLAB_USBtoUART
#UPLOAD_SPEED = 460800
BOARD=d1_mini
BUILD_DIR=build
VERBOSE=1
FLASH_DEF=4M1M
FS_TYPE=spiffs
FS_DIR=data

include /Users/karotka/Arduino/make.esp/makeEspArduino.mk
